Fixed crash on Blender 4.0
error was `AttributeError: 'BMLayerAccessEdge' object has no attribute 'crease'` on line `creases = bm.edges.layers.crease.active` since in 4.0 crease attributes were moved to just float attribute with name "crease_edge".